eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.221.127:1100/eureka/,http://10.0.221.111:1100/eureka/
server:
  port: 9995
spring:
  application:
    name: demo-zuul
  server:
    use-read-only-response-cache: false
    eviction-interval-timer-in-ms: 3000
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${credit.eureka.address}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
zuul:
  routes:
    api-a:
      path: /demo-client/**
      serviceId: demo-client